### ISSUE TITLE
backend

### ISSUE THREAD

**Issue by derlansilva** [derlansilva/sendMessages#1]
- [x]  #1. Iniciar o backend e instalar dependencias
- [x]  #2. Configurar  o Github
- [x]  #3.  Criar model User , e authenticate
- [ ]  #4. Salvar usuario no banco de dados
- [ ]  #5. Buscar usuario no banco
- [ ]  #6. Criar model Perguntas
- [ ]  #7.

**Comment by derlansilva** [comment]
- [ ]

**Comment by derlansilva** [comment]
- [ ]
